import type { AppAnalysisConfig } from './standard';
import { APP_META } from '../config';

export const LAB_ANALYSIS: AppAnalysisConfig = {
  appName: APP_META.name,
  moduleLabel: `Módulo de Evaluación Formativa Digital - ${APP_META.name}`,
  title: 'Análisis Metacognitivo del Diseño Didáctico',
  subtitle: 'Análisis cualitativo y cuantitativo del proceso cognitivo basado en el modelo de autorregulación de Zimmerman y Moylan.',
  reportSubtitle: `Evaluación del proceso de autorregulación y desempeño didáctico ${APP_META.name}`,
  appropriation: {
    blurb: 'Índice sintético que combina la exactitud de la construcción (carriles de la escalera, el puente y la cerca que quedaron correctos, 50%), la eficiencia procedimental (piezas que permanecen en carriles correctos sobre el total de colocaciones, 25%) y la reflexión formal (respuestas de formulación y anclaje más devoluciones didácticas consultadas, 25%).',
    weights: '50 / 25 / 25',
  },
  gaugeIntro: {
    title: 'Evaluación Científica de Autorregulación',
    p1: 'Estos 10 indicadores miden con precisión tu conducta al resolver las tres situaciones del laboratorio (El Volantín, El Puente y La Cerca) con regletas Cuisenaire, organizados en dos dimensiones: tu capacidad de monitoreo metacognitivo autorregulado (Zimmerman & Moylan, 2009) y tu competencia didáctico-disciplinar en la Teoría de las Situaciones Didácticas de Brousseau y los registros de representación semiótica de Duval.',
    hint: 'Haz clic en cualquier indicador para ver su fórmula y tip didáctico.',
  },
  dimB: { kicker: 'Evaluación de Dominio Disciplinar', title: 'DIMENSIÓN 2: Competencia Didáctico-Disciplinar (Brousseau & Duval)', subIndexLabel: 'Sub-índice IDCD' },
  indicators: {
    IM1: { name: 'IM1. Vigilancia Cognitiva Sostenida', authors: 'Zimmerman & Moylan (2009) — Fase de Ejecución: Autoobservación', description: 'Mide la autorregulación del tiempo entre acciones: proporción de colocaciones o retiros consecutivos de regletas separados por una pausa deliberada (entre 1,2 y 90 segundos). Previene el arrastre impulsivo de piezas.', tip: 'Antes de soltar cada regleta, detente a estimar cuánto espacio queda en el carril y qué pieza lo completa.' },
    IM2: { name: 'IM2. Proporción de Detención Reflexiva', authors: 'Zimmerman & Moylan (2009) — Fase de Ejecución: Autoobservación', description: 'Cobertura de la detención reflexiva: proporción de carriles trabajados en los que usaste Experimenta o pediste una devolución antes o durante la construcción (si solo usaste los apoyos de la actividad, el carril cuenta la mitad).', tip: 'Antes de armar cada carril, comprueba tu idea en Experimenta o pide una devolución cuando dudes.' },
    IM3: { name: 'IM3. Autocorrección y Detección de Errores', authors: 'Flavell (1979) / Zimmerman (2000) — Fase de Ejecución: Autocontrol', description: 'Capacidad de identificar y reparar un error: por cada carril donde la meta se excedió o el lado quedó mal compuesto, 50 puntos por retirar piezas tras el error (detección) y 50 por llegar luego a la configuración correcta (reparación).', tip: 'Si el carril no calza, retira la pieza que lo desajusta y reconstrúyelo con un criterio explícito, sin insistir con la misma.' },
    IM4: { name: 'IM4. Aprovechamiento de Retroalimentación', authors: 'Hattie & Timperley (2007) / Brousseau (1997) — Fase de Ejecución: Autocontrol', description: 'Nivel de uso de las devoluciones didácticas: proporción de devoluciones solicitadas que son seguidas, dentro de 5 minutos, por una acción de reajuste (colocar, retirar, experimentar o revisar el escrito).', tip: 'Tras leer una devolución, pruébala de inmediato con las regletas o reescribe tu respuesta: la pista sirve cuando cambia lo que haces.' },
    IM5: { name: 'IM5. Resiliencia al Fracaso y Reajuste Cognitivo', authors: 'Dweck (2006) / Zimmerman (2000) — Ciclo adaptativo post-error', description: 'Capacidad de reaccionar de manera inmediata y asertiva tras un error: proporción de colocaciones que exceden la meta (o componen mal un lado) seguidas, en el mismo carril, por un retiro o por una pieza de otro largo.', tip: 'Cuando una pieza no cabe, no la repitas: cambia de largo o retira lo ya puesto y piensa otra descomposición.' },
    IM6: { name: 'IM6. Alineación con la Secuencia Adidáctica', authors: 'Brousseau (1997) — Preservación de la situación adidáctica', description: 'Evaluación del orden didáctico. Penaliza los saltos de fase: pedir una devolución antes de haber actuado sobre el medio, o escribir el anclaje de una actividad antes de haber completado su construcción.', tip: 'Primero actúa sobre las regletas, luego formula por escrito lo que descubriste y solo entonces pide ayuda adicional.' },
    IM7: { name: 'IM7. Fluidez y Control de Carga Cognitiva', authors: 'Sweller (1988) — Fase de Ejecución: Autoobservación', description: 'Estabilidad de las decisiones. Mide la ausencia de movimientos redundantes: colocar una regleta y retirar de inmediato esa misma pieza del mismo carril.', tip: 'Decide con un criterio explícito antes de colocar; evita poner y sacar la misma regleta.' },
    IM8: { name: 'IM8. Intencionalidad del Ensayo y Error', authors: 'Brousseau (1997) — Interacción racional con el milieu', description: 'Eficiencia empírica. Proporción de colocaciones cuya longitud cabe matemáticamente en la meta del carril, evaluando si los intentos tienen lógica didáctica.', tip: 'Calcula cuánto falta para la meta y elige una regleta que quepa; el ensayo es válido cuando tiene una razón.' },
    IM9: { name: 'IM9. Precisión Predictiva Planificada', authors: 'Pintrich (2000) — Planificación previa a la acción', description: 'Tasa de éxito en la primera configuración: proporción de carriles validados sin retiros ni excesos previos. Refleja la solidez del análisis previo antes de someter las piezas al medio.', tip: 'Anticipa la combinación completa del carril antes de empezar a colocar: la primera configuración es la que cuenta.' },
    IM10: { name: 'IM10. Apropiación de Códigos de Formulación', authors: 'Duval (1995) / Brousseau (1997) — Fase de formulación y registros semióticos', description: 'Desempeño en la fase de formulación: proporción de las 6 preguntas formales (4 de formulación en TSD 1 y 2 anclajes en TSD 2 y TSD 3) respondidas con una explicación sustantiva.', tip: 'Explica con tus palabras qué regularidad encontraste y por qué funciona, de modo que le sirva a otra persona.' },
  },
  digcomp: {
    implement41: 'Las tres situaciones con regletas, las preguntas de formulación y los anclajes funcionan como un instrumento de evaluación formativa que diagnostica en tiempo real la comprensión de la composición y descomposición aditiva y la regularidad numérica.',
    implement42: 'Los 10 indicadores BCT (organizados en IMMZ e IDCD), el historial de colocaciones y retiros, los tiempos entre acciones y los patrones de error constituyen analíticas de aprendizaje procesables, también por actividad.',
    implement43: 'Las devoluciones didácticas graduadas (hasta tres por pregunta y anclaje) ofrecen retroalimentación oportuna y orientada a la acción sin dar la respuesta; el Diario de Campo permite que la estudiante tome decisiones sobre su propio aprendizaje.',
  },
  foundation: 'Este diagnóstico traduce la secuencia de acciones de la participante en dos dimensiones complementarias. La Dimensión A (Monitoreo Metacognitivo) se fundamenta en el modelo cíclico de autorregulación de Zimmerman y Moylan (2009), específicamente en la fase de ejecución, donde el autocontrol y la autoobservación permiten supervisar la comprensión y ajustar estrategias en tiempo real. La Dimensión B (Competencia Didáctico-Disciplinar) se sustenta en la Teoría de Situaciones Didácticas de Brousseau, donde la adquisición autónoma del saber requiere que el medio (la escalera, el puente y la cerca) funcione como un oponente con quien dialogar racionalmente, y en los registros de representación semiótica de Duval, que exigen movilizar y convertir entre el registro icónico de las regletas y el registro simbólico numérico. Ambas dimensiones se articulan con el Área 4 del marco DigCompEdu (Evaluación y Retroalimentación), que abarca el diseño de instrumentos evaluativos digitales (4.1), las analíticas de aprendizaje (4.2) y la retroalimentación orientada a la toma de decisiones (4.3). El Diario de Campo complementa los indicadores conductuales con la voz de la estudiante sobre su propio proceso, permitiendo triangular datos de comportamiento con datos de autorreporte.',
};
